name: buildSize-pipeline
on:
  pull_request:
    branches:
      - master

jobs:
  buildsize:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: Build the frontend and find buildsize
        shell: bash
        run: |
          cd frontend
          npm i
          npm run build
          nonZipBuild="frontend/build/static/js/*.chunk.js"
          ZippedBuild="frontend/build/static/js/*.chunk.js.gz"
          echo `ls -hl "nonZipBuild" | awk '{total += $5} END {print total}'`
          echo `ls -hl "ZippedBuild" | awk '{total += $5} END {print total}'`