name: Compressed Size

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2.1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          cwd: 'frontend/'